### ISSUE TITLE
Swedish translation broken

### ISSUE THREAD

**Issue by bittin** [francesco-gaglione/cosmic-money#62]
Hey!

The Swedish translation does not work as it should, could you help me to find out why?

**Comment by francesco-gaglione** [comment]
@bittin are u using the flatpak version or u instaled from source?

**Comment by bittin** [comment]
installed from source

**Comment by francesco-gaglione** [comment]
@bittin fixed, but swadish now require rework since I added a lot of new fields

**Comment by bittin** [comment]
yep it is fixed now, have reworked/updated it to in #65

sorry it took a while i am still sick and had my birthday yesterday
